export default {
    events: require("@/src/assets/icons/events.png"),
    exam: require("@/src/assets/icons/exam.png"),
    face_photo: require("@/src/assets/icons/face_photo.png"),
    faculty_list: require("@/src/assets/icons/faculty_list.png"),
    gallery: require("@/src/assets/icons/gallery.png"),
    grievance: require("@/src/assets/icons/grievance.png"),
    important_numbers: require("@/src/assets/icons/important_numbers.png"),
    learn: require("@/src/assets/icons/learn.png"),
    leave: require("@/src/assets/icons/leave.png"),
    mess: require("@/src/assets/icons/mess.png"),
    newsletter: require("@/src/assets/icons/newsletter.png"),
    next: require("@/src/assets/icons/next.png"),
    payment: require("@/src/assets/icons/payment.png"),
    profile: require("@/src/assets/icons/profile.png"),
    sbi_verification: require("@/src/assets/icons/sbi_verification.png"),
    student_login: require("@/src/assets/icons/student_login.png"),
    vahicle_pass: require("@/src/assets/icons/vahicle_pass.png"),
    welcome_booklet: require("@/src/assets/icons/welcome_booklet.png"),
    logo1: require("@/src/assets/images/agaj.jpg"),
}